server {
    listen 80;
    server_name localhost;

    # 1. 根路径加载本地静态html文件
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # 适配vue/react单页项目路由
    }
 
    # 反向代理到SpringBoot容器，直接写容器名 acc_app:8080
    location /api/ {
        proxy_pass http://app1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

