spring:
  application:
    name: DR-backend
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://8.134.115.7:3306/dr-test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080
  servlet:
    context-path: /api
my:
  jwt:
    secret: Ciallo0d000721Ciallo0d000721Ciallo0d000721Ciallo0d000721Ciallo0d000721
    exp: 7200000